# Generated by Django 3.0.7 on 2020-06-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors_books_storage', '0002_auto_20200605_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(related_name='books', to='authors_books_storage.Book'),
        ),
    ]
