# Generated by Django 3.0.7 on 2020-06-05 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors_books_storage', '0003_author_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='books',
        ),
    ]
